[package]
name = "ncrs"
version = "0.2.0"
edition = "2024"
description = "A Rust implementation inspired by Netcat."
license = "GPL-3.0-only"
authors = ["TitenQ <titenq@gmail.com>"]
homepage = "https://github.com/titenq/ncrs"
repository = "https://github.com/titenq/ncrs"
readme = "README.md"
keywords = ["netcat", "network", "tcp", "tls", "cli"]
categories = ["network-programming", "command-line-utilities"]

[dependencies]
tokio = { version = "1.36", features = ["io-std", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
figlet-rs = "0.1"
anyhow = "1.0"
tokio-rustls = "0.26"
rustls-native-certs = "0.8"
rustls-pemfile = "2.1"
directories = "6.0.0"
rcgen = "0.14.8"
time = "0.3.47"
libc = "0.2.186"
rand = "0.10.1"
base64 = "0.22.1"
nix = { version = "0.31.3", features = ["socket", "uio"] }
socket2 = { version = "0.6.3", features = ["all"] }

[package.metadata.deb]
maintainer = "TitenQ <titenq@gmail.com>"
copyright = "2026, TitenQ"
license-file = ["LICENSE.txt", "0"]
depends = "$auto"
section = "net"
priority = "optional"
assets = [
  ["target/release/ncrs", "usr/bin/", "755"],
  ["README.md", "usr/share/doc/ncrs/README.md", "644"],
  ["LICENSE.txt", "usr/share/doc/ncrs/LICENSE.txt", "644"],
]

[package.metadata.generate-rpm]
assets = [
  { source = "target/release/ncrs", dest = "/usr/bin/ncrs", mode = "755" },
  { source = "README.md", dest = "/usr/share/doc/ncrs/README.md", mode = "644" },
  { source = "LICENSE.txt", dest = "/usr/share/doc/ncrs/LICENSE.txt", mode = "644" },
]

[package.metadata.wix]
path-guid = "9D43F88C-0E8A-4CC0-80CB-9773A19F0F13"
upgrade-guid = "02A0F3B8-4E1E-40D8-AE18-9902E62E013B"
